name: time-series-forecasting
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - asn1crypto=0.24.0=py37_0
  - astor=0.7.1=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.7=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.2=py37h2e261b9_1
  - chardet=3.0.4=py37_1
  - conda=4.7.5=py37_0
  - conda-package-handling=1.3.10=py37_0
  - cryptography=2.6.1=py37h1ba5d50_0
  - cudatoolkit=9.2=0
  - cudnn=7.6.0=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py37_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libarchive=3.3.3=h5d8350f_5
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.0=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - mock=3.0.5=py37_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.16.4=py37hde5b4d6_0
  - openssl=1.1.1c=h7b6447c_1
  - pcre=8.43=he6710b0_0
  - pip=19.0.3=py37_0
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.6.8=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - python-libarchive-c=2.8=py37_10
  - pytz=2019.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scikit-learn=0.21.2=py37hd81dba3_0
  - setuptools=41.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - tensorboard=1.13.1=py37hf484d3e_0
  - tensorflow=1.13.1=gpu_py37h49933a4_0
  - tensorflow-base=1.13.1=gpu_py37h611c6d2_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.32.1=py_0
  - urllib3=1.24.1=py37_0
  - werkzeug=0.15.4=py_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - alembic==1.0.11
    - click==7.0
    - cloudpickle==1.2.1
    - configparser==3.7.4
    - databricks-cli==0.8.7
    - docker==4.0.2
    - entrypoints==0.3
    - flask==1.1.1
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - gunicorn==19.9.0
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - joblib==0.13.2
    - mako==1.0.13
    - markupsafe==1.1.1
    - mlflow==1.0.0
    - numpy==1.16.4
    - pandas==0.24.2
    - protobuf==3.8.0
    - python-editor==1.0.4
    - pyyaml==5.1.1
    - querystring-parser==1.2.3
    - scipy==1.3.0
    - simplejson==3.16.0
    - sklearn==0.0
    - smmap2==2.0.5
    - sqlalchemy==1.3.5
    - sqlparse==0.3.0
    - tabulate==0.8.3
    - websocket-client==0.56.0


